#! /bin/bash

# https://github.com/moby/moby/issues/2745
#
# Our dockerfile is in a subdirectory of espresso/docker, which is docker's build context
# Docker is unable to see into the parent directoy to copy the source code, thus we
# copy it here as a pre_build hook in
#
# This hook is evaluated at the parent level (e.g. in espresso/docker, not espresso/docker/hooks)
# it makes a directoy espresso/docker/source, and copies espresso/* inside
#
# The || is necessay as the copy returns 1 because you can't copy espresso/docker into espresso/docker/source (inside itself)
# everything else copies OK

mkdir source
cp -r ../* source || echo "copied"